#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

CONFIG="/etc/rdate-initramfs/rdate.conf"

if [ ! -s "$CONFIG" ]; then
    echo "E: rdate: Config missing, skipping rdate"
    exit 0
fi

. "$CONFIG"
if [ -z "$TIMESERVER" ]; then
    echo "E: rdate: No timeserver configured, skipping rdate"
    exit 0
fi

if ! timeout 3 busybox rdate -p "$TIMESERVER" >/dev/null; then
    echo "W: rdate: Timeserver could not be reached, rdate may not be work"
fi

# Copy config
mkdir -p -- "$DESTDIR/etc/rdate"
cp -p "$CONFIG" "$DESTDIR/etc/rdate"
